image: docker.io/nixpkgs/nix-flakes:latest

check:
  stage: build
  script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - STORE_PATHS=$(nix eval .#packages --json | jq -r .[$(nix eval --impure --expr builtins.currentSystem)][])
    - nix build --no-link $STORE_PATHS
