image: docker.io/nixpkgs/nix-flakes:latest

check:
  stage: build
  script:
    - mkdir /etc/nix && echo "experimental-features = nix-command flakes ca-references" >> /etc/nix/nix.conf
    - nix shell nixpkgs#cachix -c cachix authtoken $CACHIX_TOKEN
    - nix shell nixpkgs#cachix -c cachix use nichi
    - nix flake check -vL
    - nix shell nixpkgs#cachix -c cachix push $(nix eval .#checks --json | nix shell nixpkgs#jq -c jq -r .[$(nix eval --impure --expr builtins.currentSystem)][])
