creation_rules:
  - pgp: >-
      A1E513A77CC0D91C8806A4EB068A56CEF48FA2C1
    age: >-
      age1zxpft3utrvutt7ycfxanx8xp0gjc8mjcygv94wqw2e4w7kj29acsjx3pye,
      age14ccywqqxr7v2efqnmwrqfre4yr7xeeh5w292xpc64zp86y5sydeshkx3zr
