keys:
  age:
    - &self age16f626svywknytgas9nksmxmmgczj34yr9wekpka6khe7qx49jqgss72ms3
    - &mainframe age1y0kxvry996jt4xp60ncm0pgh3av4sflwesxsydscmll304murcusta2ng8
    - &vultr age1ku44q4wyj0duu9lrzw27r932udawa3d3566t4806mnh0rdukm4aq76wptw
    - &hydra age1e05md5fpwdptz8fwewk7jm0c0lmp4knqhq5v5z9hdlgex5l8ecmqaugw05
    - &iad0 age1x3twmsspal4s587j6fmch0qdrqnmg5cx80mvschm56dxdzel4ptqxnqj8v
    - &iad1 age1cq06gc0fr4ythzzn7z48hpqzus88grjfgmmg8zv608lwynj8pdws7unte0
    - &hel0 age1e72h2rk9zfk4l8kwmrh7rxm6j33wc86waf6ggaseyfjsa2hm4duq4hh4ez
    - &hio0 age1g4y4h0p6rzqp7qw5ll95kcgt0zfx8u047td6p7mm48ukn3ggu4eqq7pd0g
    - &nrt0 age1cj7nr3vxqcvyzay7sfzjv8qtpjplw2fwxes4dczy55yw87xavphsrksrz3
    - &sin0 age109hdqsfvm05lme2wpl640zza8lsdztqcu0al2x0zsy09w8c7pylq4leyrw
    - &sea0 age1gfqt4tz9x6y5nr0v4lgzzll7mh0yptlm2c6nv9hnps7cmu3my9qsfyrdm3
creation_rules:
  - path_regex: infra/.*
    key_groups:
      - age:
          - *self
  - path_regex: zones/.*
    key_groups:
      - age:
          - *self
          - *iad0
          - *nrt0
          - *sin0
          - *sea0
  - path_regex: nixos/mainframe/.*
    key_groups:
      - age:
          - *self
          - *mainframe
  - path_regex: nixos/hcloud/iad0/.*
    key_groups:
      - age:
          - *self
          - *iad0
  - path_regex: nixos/hcloud/iad1/.*
    key_groups:
      - age:
          - *self
          - *iad1
  - path_regex: nixos/hcloud/hel0/.*
    key_groups:
      - age:
          - *self
          - *hel0
  - path_regex: nixos/hcloud/hio0/.*
    key_groups:
      - age:
          - *self
          - *hio0
  - path_regex: modules/backup/.*
    key_groups:
      - age:
          - *self
          - *iad0
          - *iad1
          - *hio0
          - *hel0
          - *mainframe
  - path_regex: modules/gravity/.*
    key_groups:
      - age:
          - *self
          - *mainframe
          - *vultr
          - *nrt0
          - *sin0
          - *sea0
  - path_regex: modules/metrics/.*
    key_groups:
      - age:
          - *self
          - *iad0
          - *iad1
          - *hio0
          - *hel0
          - *hydra
          - *vultr
          - *nrt0
          - *sin0
          - *sea0
  - path_regex: nixos/hydra/.*
    key_groups:
      - age:
          - *self
          - *hydra
  - path_regex: nixos/vultr/nrt0/.*
    key_groups:
      - age:
          - *self
          - *nrt0
  - path_regex: nixos/vultr/sin0/.*
    key_groups:
      - age:
          - *self
          - *sin0
  - path_regex: nixos/vultr/.*
    key_groups:
      - age:
          - *self
          - *vultr
          - *nrt0
          - *sin0
          - *sea0
  - key_groups:
      - age:
          - *self
