creation_rules:
  - path_regex: nixos/rpi/.*
    pgp: >-
      068A56CEF48FA2C1
    age: >-
      age18hysd09ftl8wmrfe24pf3m0qtnlend29q3va85tzmn3fuwut7vdq7v0h5h
  - pgp: >-
      068A56CEF48FA2C1
    age: >-
      age1zxpft3utrvutt7ycfxanx8xp0gjc8mjcygv94wqw2e4w7kj29acsjx3pye
