keys:
  age:
    - &self age16f626svywknytgas9nksmxmmgczj34yr9wekpka6khe7qx49jqgss72ms3
    - &mainframe age1y0kxvry996jt4xp60ncm0pgh3av4sflwesxsydscmll304murcusta2ng8
    - &mainframe-tpm2 age1tpm1qwrqs8e6h43apd7memre4x0jnpref3lzn6kqfetwjwv24s80w5pxj72h0m4
    - &armchair age1s5rtrm895uysk36ql8tyzp7ueqrx8v6ywx4dl8lxh3lgnj9z3dfs2vkvm5
    - &vultr age1ku44q4wyj0duu9lrzw27r932udawa3d3566t4806mnh0rdukm4aq76wptw
    - &iad0 age1x3twmsspal4s587j6fmch0qdrqnmg5cx80mvschm56dxdzel4ptqxnqj8v
    - &hel0 age1e72h2rk9zfk4l8kwmrh7rxm6j33wc86waf6ggaseyfjsa2hm4duq4hh4ez
    - &hel1 age1z92a3t3eyd4r0jswpc5yahcd0v3964uklm7v77w60wx86hcspymslsqn3a
    - &hio0 age1g4y4h0p6rzqp7qw5ll95kcgt0zfx8u047td6p7mm48ukn3ggu4eqq7pd0g
    - &nrt0 age1cj7nr3vxqcvyzay7sfzjv8qtpjplw2fwxes4dczy55yw87xavphsrksrz3
    - &sin0 age109hdqsfvm05lme2wpl640zza8lsdztqcu0al2x0zsy09w8c7pylq4leyrw
    - &sea0 age1gfqt4tz9x6y5nr0v4lgzzll7mh0yptlm2c6nv9hnps7cmu3my9qsfyrdm3
creation_rules:
  - path_regex: infra/.*
    key_groups:
      - age:
          - *self
  - path_regex: zones/.*
    key_groups:
      - age:
          - *self
          - *iad0
          - *nrt0
          - *sin0
          - *sea0
  - path_regex: nixos/mainframe/.*
    key_groups:
      - age:
          - *self
          - *mainframe
          - *mainframe-tpm2
  - path_regex: nixos/hcloud/iad0/.*
    key_groups:
      - age:
          - *self
          - *iad0
  - path_regex: nixos/hcloud/hel0/.*
    key_groups:
      - age:
          - *self
          - *hel0
  - path_regex: nixos/hcloud/hel1/.*
    key_groups:
      - age:
          - *self
          - *hel1
  - path_regex: nixos/hcloud/hio0/.*
    key_groups:
      - age:
          - *self
          - *hio0
  - path_regex: modules/backup/.*
    key_groups:
      - age:
          - *self
          - *iad0
          - *hio0
          - *hel0
          - *hel1
          - *mainframe
          - *mainframe-tpm2
  - path_regex: modules/gravity/.*
    key_groups:
      - age:
          - *self
          - *mainframe
          - *mainframe-tpm2
          - *armchair
          - *vultr
          - *nrt0
          - *sin0
          - *sea0
  - path_regex: modules/metrics/.*
    key_groups:
      - age:
          - *self
          - *iad0
          - *hio0
          - *hel0
          - *hel1
          - *vultr
          - *nrt0
          - *sin0
          - *sea0
  - path_regex: nixos/vultr/nrt0/.*
    key_groups:
      - age:
          - *self
          - *nrt0
  - path_regex: nixos/vultr/sin0/.*
    key_groups:
      - age:
          - *self
          - *sin0
  - key_groups:
      - age:
          - *self
