keys:
  age:
    - &local age14ccywqqxr7v2efqnmwrqfre4yr7xeeh5w292xpc64zp86y5sydeshkx3zr
    - &other age1zxpft3utrvutt7ycfxanx8xp0gjc8mjcygv94wqw2e4w7kj29acsjx3pye
    - &iad0 age1x3twmsspal4s587j6fmch0qdrqnmg5cx80mvschm56dxdzel4ptqxnqj8v
    - &iad1 age1cq06gc0fr4ythzzn7z48hpqzus88grjfgmmg8zv608lwynj8pdws7unte0
    - &hel0 age1e72h2rk9zfk4l8kwmrh7rxm6j33wc86waf6ggaseyfjsa2hm4duq4hh4ez
    - &hio0 age1g4y4h0p6rzqp7qw5ll95kcgt0zfx8u047td6p7mm48ukn3ggu4eqq7pd0g
creation_rules:
  - path_regex: infra/.*
    key_groups:
      - age:
          - *local
  - path_regex: zones/.*
    key_groups:
      - age:
          - *local
          - *iad0
          - *other
  - path_regex: nixos/mainframe/.*
    key_groups:
      - age:
          - *local
          - *other
  - path_regex: nixos/hcloud/iad0/.*
    key_groups:
      - age:
          - *local
          - *iad0
  - path_regex: nixos/hcloud/iad1/.*
    key_groups:
      - age:
          - *local
          - *iad1
  - path_regex: nixos/hcloud/hel0/.*
    key_groups:
      - age:
          - *local
          - *hel0
  - path_regex: nixos/hcloud/hio0/.*
    key_groups:
      - age:
          - *local
          - *hio0
  - path_regex: modules/backup/.*
    key_groups:
      - age:
          - *local
          - *iad0
          - *iad1
          - *hio0
          - *hel0
          - *other
  - path_regex: modules/gravity/.*
    key_groups:
      - age:
          - *local
          - *iad0
          - *iad1
          - *hio0
          - *hel0
          - *other
  - path_regex: modules/metrics/.*
    key_groups:
      - age:
          - *local
          - *iad0
          - *iad1
          - *hio0
          - *hel0
          - *other
  - path_regex: nixos/hydra/.*
    key_groups:
      - age:
          - *local
          - *other
  - path_regex: nixos/vultr/nrt0/.*
    key_groups:
      - age:
          - *local
          - *other
  - path_regex: nixos/vultr/sin0/.*
    key_groups:
      - age:
          - *local
          - *other
  - key_groups:
      - age:
          - *local
