[ko]
src.github = "google/ko"
fetch.github = "google/ko"

[auth-thu]
src.github = "z4yx/GoAuthing"
fetch.github = "z4yx/GoAuthing"

[butane]
src.github = "coreos/butane"
fetch.github = "coreos/butane"

[k0sctl]
src.github = "k0sproject/k0sctl"
fetch.github = "k0sproject/k0sctl"

[kubeone]
src.github = "kubermatic/kubeone"
fetch.github = "kubermatic/kubeone"

[material-decoration]
src.git = "https://github.com/Zren/material-decoration"
fetch.github = "Zren/material-decoration"
