[auth-thu]
src.github = "z4yx/GoAuthing"
fetch.github = "z4yx/GoAuthing"
passthru = { vendorSha256 = "sha256-LSGyy4i4JWopX54wWXZwEtRQfijCgA618FeQErwdy8o=" }

[smartdns-china-list]
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"

[rait]
src.git = "https://gitlab.com/NickCao/RAIT"
fetch.git = "https://gitlab.com/NickCao/RAIT"
passthru = { vendorSha256 = "sha256-pMltPbi1tOfxIBjLHtSxqSQUy7sMTDa8YJ9PeQp3b3k=" }

[wemeet]
src.manual = "2.8.0.3"
fetch.url = "https://updatecdn.meeting.qq.com/cos/3cdd365cd90f221fb345ab73c4746e1f/TencentMeeting_0300000000_2.8.0.3_x86_64_default.publish.deb"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.3."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.3/zhwiki-$ver.dict"

[mokutil]
src.github = "lcp/mokutil"
fetch.github = "lcp/mokutil"

[prometheus_bot]
src.git = "https://github.com/inCaller/prometheus_bot"
fetch.github = "inCaller/prometheus_bot"
passthru = { vendorSha256 = "sha256-Y8cUYjhJxndvV8Ib4XIblZ9Z0SvnkPzNTDMjEd3R4II=" }

[karma-bin]
src.github = "prymitive/karma"
fetch.url = "https://github.com/prymitive/karma/releases/download/$ver/karma-linux-amd64.tar.gz"
