[ko]
src.github = "google/ko"
fetch.github = "google/ko"

[auth-thu]
src.github = "z4yx/GoAuthing"
fetch.github = "z4yx/GoAuthing"
passthru = { vendorSha256 = "sha256-SCLbX9NqMLBNSBHC3a921b8+3Vy7VHjUcFHbjidwQ+c=" }

[k0sctl]
src.github = "k0sproject/k0sctl"
fetch.github = "k0sproject/k0sctl"

[material-decoration]
src.git = "https://github.com/Zren/material-decoration"
fetch.github = "Zren/material-decoration"

[qv2ray]
src.git = "https://github.com/Qv2ray/Qv2ray"
src.branch = "dev"
git.fetchSubmodules = true
fetch.github = "Qv2ray/Qv2ray"

[qv2ray-plugin-ss]
src.git = "https://github.com/Qv2ray/QvPlugin-SS"
src.branch = "dev"
git.fetchSubmodules = true
fetch.github = "Qv2ray/QvPlugin-SS"

[v2ray-domain-list-community]
src.git = "https://github.com/v2fly/domain-list-community"
fetch.github = "v2fly/domain-list-community"
passthru = { vendorSha256 = "sha256-wMwGqVqCSJ3801sfou0je/Cp1COMPYY0GH+Sx1Jev8s=" }

[v2ray-geoip]
src.git = "https://github.com/v2fly/geoip"
src.branch = "release"
fetch.github = "v2fly/geoip"
git.branch = "release"

[smartdns-china-list]
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"

[rait]
src.git = "https://gitlab.com/NickCao/RAIT"
fetch.git = "https://gitlab.com/NickCao/RAIT"
passthru = { vendorSha256 = "sha256-55Zu1g+pwTt6dU1QloxfFkG2dbnK5gg84WvRhz2ND3M=" }

[chasquid]
src.github_tag = "albertito/chasquid"
fetch.github = "albertito/chasquid"
passthru = { vendorSha256 = "sha256-1H1zTRzX6a4mBSHIJvLeVC9GIKE8qUvwbgfRw297vq4=" }

[traefik-certs-dumper]
src.git = "https://github.com/ldez/traefik-certs-dumper"
fetch.github = "ldez/traefik-certs-dumper"
passthru = { vendorSha256 = "sha256-4v8We/3FgFqXxlGaoQXQ6EQn8bbAkMrWkjfTUo2U8FU=" }

[tslib]
src.github = "libts/tslib"
fetch.github = "libts/tslib"
