[auth-thu]
src.github = "z4yx/GoAuthing"
fetch.github = "z4yx/GoAuthing"
passthru = { vendorSha256 = "sha256-LSGyy4i4JWopX54wWXZwEtRQfijCgA618FeQErwdy8o=" }

[smartdns-china-list]
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"

[rait]
src.git = "https://gitlab.com/NickCao/RAIT"
fetch.git = "https://gitlab.com/NickCao/RAIT"
passthru = { vendorSha256 = "sha256-T/ufC4mEXRBKgsmIk8jSCQva5Td0rnFHx3UIVV+t08k=" }

[wemeet]
src.manual = "3.11.0.402"
fetch.url = "https://updatecdn.meeting.qq.com/cos/9b74d4127a16a011db8cb6300fa5fbc9/TencentMeeting_0300000000_$ver_x86_64_default.publish.deb"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict"

[riscv-openocd]
src.git = "https://github.com/riscv/riscv-openocd"
fetch.github = "riscv/riscv-openocd"
git.fetchSubmodules = true

[bird-babel-rtt]
src.git = "https://github.com/NickCao/bird"
src.branch = "babel-rtt"
fetch.github = "NickCao/bird"
