# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  ko = {
    pname = "ko";
    version = "v0.8.3";
    src = fetchgit {
      url = "https://github.com/google/ko";
      rev = "v0.8.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1ccw09ghpnxsv88mp6y6amyif95hrq004m8x3albbxda77whxb1q";
    };
  };
  material-decoration = {
    pname = "material-decoration";
    version = "e652d62451dc67a9c6bc16c00ccbc38fed3373dd";
    src = fetchgit {
      url = "https://github.com/Zren/material-decoration";
      rev = "e652d62451dc67a9c6bc16c00ccbc38fed3373dd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "182hqn4kbh0vmnbhj7nrqx2lypkddd6appp5y4kqinnw8dmpdyqx";
    };
  };
  auth-thu = {
    pname = "auth-thu";
    version = "v2.0.3";
    src = fetchgit {
      url = "https://github.com/z4yx/GoAuthing";
      rev = "v2.0.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1z1anpp16d01ncp2bg1ahnyn0707xnavhbaqhddjhzw78zsh120q";
    };
  };
  kubeone = {
    pname = "kubeone";
    version = "v1.2.1";
    src = fetchgit {
      url = "https://github.com/kubermatic/kubeone";
      rev = "v1.2.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1abm7735c4pjv31pfggkvia7br19zbhjpp2w0n5zckwrjm9hxns6";
    };
  };
  k0sctl = {
    pname = "k0sctl";
    version = "v0.8.4";
    src = fetchgit {
      url = "https://github.com/k0sproject/k0sctl";
      rev = "v0.8.4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "08k0aa73kb4hs4zl8a2nmasag0czmppb2r0s1afj287c2a4ynw73";
    };
  };
  butane = {
    pname = "butane";
    version = "v0.11.0";
    src = fetchgit {
      url = "https://github.com/coreos/butane";
      rev = "v0.11.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1s4rkq7mj1lyi8h47jyfy3qygfxhrmpihdy8rcnn55gcy04lm0qc";
    };
  };
}