vultr:
    api_key: ENC[AES256_GCM,data:ggWaY2oXE133QJRirWcoO8mmdmNxyPbs7B4tUJVUm26ep/xb,iv:SsO/9woiKcC9vb6FrHBaA9e+CMz0BluQo7amjqrHces=,tag:w2tJ7rh2zcOE7ZSKxgbxBA==,type:str]
nixos:
    key: ENC[AES256_GCM,data:2cVLZ5VzAiBM1FDb37UGRomMC72oHKjc/yFMd4ahNs2hmC8sNGK7KH54Yc8MwFWWnJN2Ui/nrrFzl16rPs+fDQH8oePih7xOCFPMZAFW7QGEpd3mOqvN1b7NyVPX6kx0+CW0KCTV22ns43ilMmfG5Q7Dyy+Vbi2HOUzba0eZDSo+8fyDtZeIYFcA8sCU03BV5A5cqPdOhLg8abrKGRrOhFHJcMo986elU09L8JoagSeuuyjSETyzku+6jaoX,iv:S33sKJ3yhV8QeOtbEjBLsDLaknwG3/rOOjaplANW54g=,tag:qvJHQ8cPaFW+3BCC7KF1Ng==,type:str]
hydra:
    password: ENC[AES256_GCM,data:jUA3LAUPRWjS4wxuyW2xlJmhLPeQJCKNdPMASWDlRSs=,iv:K12eXREO6LtJw/BeOrdE+m2zAQZVSnzumXKK6gK8sP0=,tag:MSnbp2g5TYxNDwnAUscP/Q==,type:str]
hcloud:
    token: ENC[AES256_GCM,data:rYOf8EydPldRHKZi9N5fgrp1RFa6+M+lYYu2rkF7tA9dS2H3iME0uYvMdD1A6+QtrMq48iyWDBdgcuOdmO7KuA==,iv:fOBMc0xqzxXFyP5Ie3EnrybHLz0lrWtqX8cV5sBlVLU=,tag:2UZroXRK/IfKVAj7Ph2kQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxpft3utrvutt7ycfxanx8xp0gjc8mjcygv94wqw2e4w7kj29acsjx3pye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYmhqU2UraG05V2NnTFNy
            aVBjRDlESEljSWZlbm9SckNRbmJ1YUZlWDBZCmtseURkbHRncDllV1JMSmV3TSt6
            dTcra1JhbHppL2ZCOGt2VE1vOW5pTUUKLS0tIDNacGZ3dnJwTm5HbXdwY0VFY09l
            VjEySW9FTVVHRWxWWlJFY25mQXdrczgKVwB786HNpoXMppqHZNhlcR+NwA+hnKY4
            KjnKsYQLyfnKowq31fXXGcU581vgqh+l/EpROPoWb+vDy1jaZGOUEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ccywqqxr7v2efqnmwrqfre4yr7xeeh5w292xpc64zp86y5sydeshkx3zr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVmErQi9vQlRHVXI0RldW
            TGJIa0JYTEJpTDdOMk9BQjNWM0R1K1BraVcwClRZTWVIL1hTc2I0TDFrVWlzNHhH
            azFIQWFhT3BlTkFwNllZVzhFdnVQVjAKLS0tIDg0VEFiaGltVGZLNEJmT2JlS2FU
            TmNsbjFRTnVYODI4N3RVdjVnYkpFQTgKvMZLtWThD0kPyEm5jdb5Hp72y/7Z+gsf
            ARvFj6KUwIQLB5+b61OqV7r+CNB8ImPhe2hRUx7GN43DmbES1fq75w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T05:06:34Z"
    mac: ENC[AES256_GCM,data:lA5VSFC1NWzkmUk9RJyavPTglRc9JNkyZ60Hjb4O6f9+IlfPZ82tHs7WCBnvFSUMV2B/NPQf+bWN37D2iO6WZdWk+HB19JaAop0TALfNI7pGJVWEDLGr4bniqGoQgimz+V9EZAg6YvN2YORXp5AqszVyPhgSQw1G6axuQ3LubnE=,iv:zdErc8gQzzmOJDDNYTeix/md+TijfYKMSghDIHSxQ70=,tag:9IWRhB3mLuFAhlkMS0GsDA==,type:str]
    pgp:
        - created_at: "2023-08-08T11:27:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DKoktvEl14EoSAQdAGZeVVWBto+QmLuX/6qwp/U8Pf4SlhysS/atEQ72F0l4w
            YMv9GIttF1NwHPlzqMWf49pn959zz5AGe4CT6dDyFdl8zzHO9pYQ5qTJJA5D4L3r
            0lEBXhm0gKAUldFj+aof+5aEmnycJ/iQubdR7T+r/8KfiWpLIiDZnYpYd5zKdIMH
            Q5Al3O5D+mOrSzOW+IfVqU4zYmiTSRGB2SQ5BM0qvSQowdI=
            =LI8w
            -----END PGP MESSAGE-----
          fp: A1E513A77CC0D91C8806A4EB068A56CEF48FA2C1
    unencrypted_suffix: _unencrypted
    version: 3.7.3
