vultr:
    api_key: ENC[AES256_GCM,data:EvjDCMx2DPwNfwHrS4wVBS8CMzAdK4aWTvJGdOu8w39cFEz1,iv:SsO/9woiKcC9vb6FrHBaA9e+CMz0BluQo7amjqrHces=,tag:FAVDmK+fwnkpY4JUId35fQ==,type:str]
nixos:
    key: ENC[AES256_GCM,data:ogoFCeonL6rcyEBm45XDxN8NH1Y1DHST1uNEre/meY4N1e1tExrHnIsBiPwO6mH+kTfL0LmdPt6QPeg5/SY5soFs+Gmc7JXiVBXYJGjAxxAMkJnZ5/NJRvqGLIf2vhNsofBBCdkwmVz03KjF/9yH32hBRo2jwGW5RqY8hLG5eHjksMgMlFqAmxHjRW39oipkXyV+6VAdJ6CHZG4ZT0wxVPTZXkOgInnKOMfZlxtphI6eU+gcWpfiqtwWBeYN,iv:S33sKJ3yhV8QeOtbEjBLsDLaknwG3/rOOjaplANW54g=,tag:Op9933kJs8tTBdoiJ//RWw==,type:str]
    rpi: ENC[AES256_GCM,data:8pPuMBMiZWpRP74u0eITOTwjeKRWSxSMDmr2YpqwR/iI+h0bYpv2IAEB0nyZcqwQVqPOZ9F+Oqy0GoPXqkIUUn8nS8F834HFY/piEmkC6xMJg8TN2EA+c6tyMfQ+eJHad9uJ3FMWKdKJcDbXsusZvPFSO023tBz6gszZFmKDyfkokbvnZzCxK20BeDMTdzTksjYsSg6BwOujRq6fIc1GuqUMSBU69w6RZCQhPlhC9tDM8swdahAEiubGukQg,iv:QDEyha4e7LceKZl1JDhbXXuWZnWpcEEruul9ECgOnCE=,tag:yXkYiQst7F1ySDi6jB9exg==,type:str]
gandi:
    key: ENC[AES256_GCM,data:vvs1qrws5SCSq281yABh5US6ZvAGAZ2t,iv:txfFRYO4YqOcz1rGfCgnSa7i7lUSzjpf0sEBeb2In8M=,tag:LuTZtQ3t8x9doBcpbEAjUA==,type:str]
hydra:
    password: ENC[AES256_GCM,data:umXK/VkypnUKrZTcwpKI6lL5m+8G2najz/hOfKNuSFc=,iv:K12eXREO6LtJw/BeOrdE+m2zAQZVSnzumXKK6gK8sP0=,tag:n4Ha7GRwXNG2LJ4CeZiNHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxpft3utrvutt7ycfxanx8xp0gjc8mjcygv94wqw2e4w7kj29acsjx3pye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UHYzVG00SmZza3FmbUQw
            UTFJRjV0NUxtaUhDRlAxak1jcE9YNFo2MGh3CnlLcjMyNUR1eHQzR2N3d2V3Umw5
            WmZ2OHpQZ0JsN3RuYys1VmtyVEEwSmcKLS0tIDFCRHRNNHJ5andYdWdua2JuTk1n
            ZFg0UEhlTk5XT2gxdkdxZFVwUFpNOE0KzD/9xZ7JyPNOJyzFXaqH/b1AlTQwswWk
            f+DjSeHrbK9YVk0jsllrVeMC/wEqh4CGohOPWtqn0MC8wYEN7t6q/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-09T13:28:37Z"
    mac: ENC[AES256_GCM,data:jnokR116ZOyo+cX83bzqImuqbgVHedKmBDl+sepHGAwiQoYN7m5mf6f/lmlo0YaCm9XgKaa8wSfKOW2NHaX9sI9keBoBVs9hMEIzQ0oNGAnBLGN3jTOJ0dTQ7DkOtPrxSeGyGumcOY8D9jKylySZNkpWlSBDXajxV29zARi2wWY=,iv:N5aIJ7NJMa3U1hrYgqAyhKeeSDlkNW6NZT2/1zWWrgE=,tag:z4e5h3TLVRsyIVj+Bpbo2w==,type:str]
    pgp:
        - created_at: "2022-08-11T06:32:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DKoktvEl14EoSAQdAduszqrFOGU4xfoYi82IKWjCXFO8M5BcB0Jl5Z1LsIDww
            +k0xXnjC84Oeff+oO4JjanbBoDBh8uWHaKwtBshxwWjeRyiVl892fPAl+P14zJPO
            0lEB1Xx/7Lk1SzM8ZpBR9ghlwLTZ+vn/vNzr/GtResUEFT4ixGnpKRGG1oY/D5GL
            dBS5gUPXh58EE+/3LICC0f0pMSskFDsBOJFoKzDhbmKsv9o=
            =2EBo
            -----END PGP MESSAGE-----
          fp: A1E513A77CC0D91C8806A4EB068A56CEF48FA2C1
    unencrypted_suffix: _unencrypted
    version: 3.7.3
