vultr:
    api_key: ENC[AES256_GCM,data:avr/7vRxUK259TMZzM/fQGm2T4Ok0C6NmZgx/KdcVhxGlZTd,iv:MTbYjXIK31oeEWAOqH+Brbj9l2KUQ8TNVh6ZiHtjmGw=,tag:C0ygyv6dtbhm99C/wVbg7Q==,type:str]
minio:
    access_key: ENC[AES256_GCM,data:tdm9Tyne7sjwEoU3GWoJ/CLnHYdka+akEJu1EwkRlks=,iv:uy5se8lOH2fWTLTOkOIX5JGf4/gL8joBhle2Ic3Z9ow=,tag:x26yAII2tPHP1esEOFadmQ==,type:str]
    secret_key: ENC[AES256_GCM,data:RzE1Ih58WPQCZfoHxIvITM2ktN7Ayhil0yBb+Bsc0U0=,iv:BkPlceQHsgoeEl+dvUy4XvCELydH+SLyZVIM4QT8YI8=,tag:HgXGXxms9YwU55oLA1d2gA==,type:str]
nixos:
    key: ENC[AES256_GCM,data:iWpR5pG+RnVL+nZBvnyxNSYYNS7Iumc6HtkGfoNRwwvS/qWzlH5qADjMhn692Jdj4LpzZPMmuviOHuTQGPVI4H2mWxjmibnV++k26ilYbgZP/9pDr6vsmOrLYJknNU77FexYRAmVkQawVL3gzeIxRDV/Z3kRaIzDNoW+KCre1BIV0pzUGM+y8XDjZtkWnWaqxQ8xkHW3kx9bi1eWKzu8Fs3rIHjsIcOBW25kMDbgDMfpBXp8wdjct5HllmSg,iv:5aRrvX2GPE0zYdH8i+//Du7bEO0iUHI1djYaBoJPWSY=,tag:4YPWpiBal/++2MaSaGp4OA==,type:str]
gandi:
    key: ENC[AES256_GCM,data:byH91JvYGdaGdMRe29esAgj1ciO/EEPh,iv:amVTNraNYHS9vGl866XXQ8TPAEUki8KqTLVvTnHVG4Y=,tag:jrI1t5gisxyLvYWRto0v0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fzzsuff82thukjus3dh6z68suh90xupv04pf9dwlm9pstptkfdasmnjhc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QXFCWFhLUEFGclIzY0Jx
            Y3lBTngrTWUzLytZLzhTRVJpRWQ4RkVldmhjCkVSSWJiWGk4RGtTdklncHplZGdv
            cGd1RUhBSlMySGxIUEJ1TWNMb0VCSG8KLS0tIGtrcnNBb3h2Yk94ZTdkUGtBQjR6
            c3RSZDM0Y2ZCVGFKK3BpSThvU2YrWk0KAHD6j0aehdr13PBndXkBY+yayQt4Dluw
            rOB5bdrKkrj9cEzZORhCiRb+HLkPqMV6GBwEcHm56BHM5urZf9TUrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-09T08:03:54Z"
    mac: ENC[AES256_GCM,data:fSK6Tlndx8nHUuc6WYU777GGuemNbF4Jb5lIDsaMlqaLao591ClZQ/WKjX7u4EyXqn2VGyRTRlBl0kMScYFQlSAmAOkAcshn/wQQ8jmCnasvHI7doln0VidagfFHhlqEiURa3ylO45t7JQprp259Vjbn7T354dc1apoplW+0+0M=,iv:ZTgYl0KQw6Z1OW5ANFd4njl2s6N/oyrgAlHjaVlUblc=,tag:NPNLbJwbrnbqm3QGYl6rIQ==,type:str]
    pgp:
        - created_at: "2022-04-09T06:04:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DKoktvEl14EoSAQdAYiRFtc+2jB1RhOk4B7HfeIGCghfFo9Gm/y42o+ngw1Mw
            wFluEG37cqtJzoK9OvQAW0AiipkHMSE8Lb7jhBWNZCv3tRDqs4CmE4ZfOlNMI27e
            0lwBcjLulYGJwMs6JYiwN/I3EX3uATaMKbLywJbgyTSzmK0ArCcFdVRwk8xNAD3l
            p2aH5rNY8PQu5JfGbTi3hNYQ8SkegfjjH51zDJ9ODX9J5/LMeKDDlVZ/cowJhQ==
            =7Nel
            -----END PGP MESSAGE-----
          fp: 068A56CEF48FA2C1
    unencrypted_suffix: _unencrypted
    version: 3.7.1
