vultr:
    api_key: ENC[AES256_GCM,data:ggWaY2oXE133QJRirWcoO8mmdmNxyPbs7B4tUJVUm26ep/xb,iv:SsO/9woiKcC9vb6FrHBaA9e+CMz0BluQo7amjqrHces=,tag:w2tJ7rh2zcOE7ZSKxgbxBA==,type:str]
nixos:
    hel0: ENC[AES256_GCM,data:Y4KahhPHhG6GzJQZBcy+3ifNeTzgw6IvrAAe6WkrdO/hTVRU2bv9S7IwmGSIoTI14GWgNQ0JMbN+2l9dSsLPGqnfARk/xk54hbHYf3qfytTF0d0WnirXB4ubykFRRHjG36WsVg1dmUWNQciHuSlvgfXSFvQ8eHtBCr7mKEdpP+T8QU2RVcmgR3nLFcy4DKEkgdMppb0lz6yoGFsYLlWCVtQMnl2evGVghOMNQOh4YOKHnp6nCL9rW/gQqm8J,iv:cKR1T6df0ADi3Z8r9oz9j3yumJfKBMe/uvib+dOJV1k=,tag:WTX3guJVxRlNwppG/Eifpg==,type:str]
    key: ENC[AES256_GCM,data:2cVLZ5VzAiBM1FDb37UGRomMC72oHKjc/yFMd4ahNs2hmC8sNGK7KH54Yc8MwFWWnJN2Ui/nrrFzl16rPs+fDQH8oePih7xOCFPMZAFW7QGEpd3mOqvN1b7NyVPX6kx0+CW0KCTV22ns43ilMmfG5Q7Dyy+Vbi2HOUzba0eZDSo+8fyDtZeIYFcA8sCU03BV5A5cqPdOhLg8abrKGRrOhFHJcMo986elU09L8JoagSeuuyjSETyzku+6jaoX,iv:S33sKJ3yhV8QeOtbEjBLsDLaknwG3/rOOjaplANW54g=,tag:qvJHQ8cPaFW+3BCC7KF1Ng==,type:str]
    hcloud: ENC[AES256_GCM,data:WcvPw9UfjDri57IxaH5JfKxvnwVuTC11uUiB+nC0CDJPqksboEkljH1bjob1QD9GUj223Rd7nXCIAaszQunbi701iWU7HMgIUVjjT7hfTbgAA1Zvzx4S6woNwXarrlx9n72LQdH3aqKfQoPe2aunBfxnh91HaDuin3wPzuc5BJRjVIDbIEwJOJN35dpRYLw/5rsbMEuUJvoce5nfCd+rxROZWRrOSF0I77dOgmRT3t9atBy+tTuJ91l5RYc9,iv:RGQcrDts1vyIhkNIeYiERkyVpnff4Zs3xADJ2VfU35E=,tag:3ZkwKiUXEhes13FzU19Btg==,type:str]
hydra:
    password: ENC[AES256_GCM,data:jUA3LAUPRWjS4wxuyW2xlJmhLPeQJCKNdPMASWDlRSs=,iv:K12eXREO6LtJw/BeOrdE+m2zAQZVSnzumXKK6gK8sP0=,tag:MSnbp2g5TYxNDwnAUscP/Q==,type:str]
hcloud:
    token: ENC[AES256_GCM,data:rYOf8EydPldRHKZi9N5fgrp1RFa6+M+lYYu2rkF7tA9dS2H3iME0uYvMdD1A6+QtrMq48iyWDBdgcuOdmO7KuA==,iv:fOBMc0xqzxXFyP5Ie3EnrybHLz0lrWtqX8cV5sBlVLU=,tag:2UZroXRK/IfKVAj7Ph2kQg==,type:str]
keycloak:
    token: ENC[AES256_GCM,data:z7BWOnx9t9rbNEXBYR3KHjZJanZc8wNa3vqAR16t6Zw=,iv:FaXKL9Ik2TA0+ArgiN2A34EDTDNpTCHHQN//NC91LMg=,tag:vk+1Na+xnN0oAlVcMjB0NQ==,type:str]
tofu: ENC[AES256_GCM,data:zJkDuzOit1qerpEfcTAa1imMFbaK1m9x/STwAP/TpKgqZLwZ3x9RhATa80/IcBGNfEN07HR5/qZNKSB2UQJb5ZjkKYnO6fx1+M89XsR6aTTtnuZNIoo=,iv:Xv/1rmeuz/6AoeldfX/CDVNbHQStgCg2NlIW2FsM1UY=,tag:uSeyAehnc+iOoYfbH6mUhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ccywqqxr7v2efqnmwrqfre4yr7xeeh5w292xpc64zp86y5sydeshkx3zr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Rk53TGdlNWJGMUt1V3FV
            REpSSWt6L0IxQ1lSdGV2aENhMjlDYXZ2VjFJCnpzdU5SdzdlTXkrNmFrVG1CdkR6
            cFRGREZFSCs0WGpvc0FBaCsvVHY5Sk0KLS0tIFVNc0JYTjZLek41Z3A5MURac0hz
            bTRmMjVvT1daYkI3YzVINXl0NjVPWXcKX25D0ghm6/ClBYtYORbHHUJbT4KYH0v6
            cJbtXWuys63GfkrdpOovYxKwoOXs7in1+IU+SPSwnHIz9SbLw5k7FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T00:19:04Z"
    mac: ENC[AES256_GCM,data:ciSqHx4qqPTke60iR7lSFsfaxLoJeq/C0q62yCIC5lpj1K1pFXWcaJPZufXE8L7Va2sq7D+h2OTIdXeUvKKhrTtPyqPcled4sKYckyIVT9Bs8wWb+sx1Kb1ER/okzPg+1r1mxGqzSwYThxLiZN+AwFjBCaZb7tL8+I713so8rak=,iv:HriDdzBOnCbc5x7+McPoZpStkQ1QFBn8DMYLTEiIqMo=,tag:eY64YZuSv03E9SaZ5FqbEA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
