# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "usbhid"
  ];

  boot.loader.efi.efiSysMountPoint = "/efi";

  boot.kernel.sysctl."net.ipv4.tcp_l3mdev_accept" = lib.mkForce 1;

  boot.kernelPatches = lib.singleton {
    name = "enable-xfrm-interface";
    patch = null;
    extraStructuredConfig = with lib.kernel; {
      XFRM_INTERFACE = yes;
    };
  };

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [
        "defaults"
        "mode=755"
      ];
    };
    "/efi" = {
      device = "/dev/nvme0n1p4";
      fsType = "vfat";
      options = [ "umask=0077" ];
    };
    "/nix" = {
      device = "/dev/disk/by-label/ROOT";
      fsType = "btrfs";
      options = [
        "compress=zstd"
        "subvol=nix"
      ];
    };
    "/persist" = {
      device = "/dev/disk/by-label/ROOT";
      fsType = "btrfs";
      neededForBoot = true;
      options = [
        "compress=zstd"
        "subvol=persist"
      ];
    };
  };

  environment.persistence."/persist" = {
    files = [
      "/etc/machine-id"
      "/etc/ssh/ssh_host_ed25519_key"
      "/etc/ssh/ssh_host_ed25519_key.pub"
      "/etc/ssh/ssh_host_rsa_key"
      "/etc/ssh/ssh_host_rsa_key.pub"
    ];
    directories = [
      "/var"
      "/root"
      "/home"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault false;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
