name: nix
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: '${{ inputs.ref }}'
    - uses: docker/setup-qemu-action@v1
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux
          trusted-public-keys = hydra.nichi.co-0:P3nkYHhmcLR3eNJgOAnHDjmQLkfqheGyhZ6GLrUVHwk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.nichi.co https://cache.nixos.org/
    - uses: shimataro/ssh-key-action@v2
      with:
        key: '${{ secrets.SSH_PRIVATE_KEY }}'
        known_hosts: unnecessary
    - run: nix shell .#deploy-rs -c deploy -s
