name: deploy-rs
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
jobs:
  check:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: '${{ inputs.ref }}'
    - uses: docker/setup-qemu-action@v1
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux
    - uses: cachix/cachix-action@v10
      with:
        name: nickcao-staging
    - uses: shimataro/ssh-key-action@v2
      with:
        key: '${{ secrets.SSH_PRIVATE_KEY }}'
        known_hosts: unnecessary
    - run: nix shell .#deploy-rs -c deploy -s
